language: node_js
node_js:
  - node 
env:
  global:
    - CC_TEST_REPORTER_ID=448b6b92849c7a2e3a40d51febb0e8571efffa675fd79b27db70f4218819c468
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - make lint
  - make test-coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT 
notifications:
  email: false